#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinansAsistan.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DIMER2022")]
	public partial class dbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDIMER_TBL_NAKITAKIS_NEW(DIMER_TBL_NAKITAKIS_NEW instance);
    partial void UpdateDIMER_TBL_NAKITAKIS_NEW(DIMER_TBL_NAKITAKIS_NEW instance);
    partial void DeleteDIMER_TBL_NAKITAKIS_NEW(DIMER_TBL_NAKITAKIS_NEW instance);
    partial void InsertTBLFATUEK(TBLFATUEK instance);
    partial void UpdateTBLFATUEK(TBLFATUEK instance);
    partial void DeleteTBLFATUEK(TBLFATUEK instance);
    partial void InsertDIM_NDI_EXIMBANK(DIM_NDI_EXIMBANK instance);
    partial void UpdateDIM_NDI_EXIMBANK(DIM_NDI_EXIMBANK instance);
    partial void DeleteDIM_NDI_EXIMBANK(DIM_NDI_EXIMBANK instance);
    #endregion
		
		public dbDataContext() : 
				base(global::FinansAsistan.Properties.Settings.Default.DIMER2022, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DIMER_TBL_NAKITAKIS_NEW> DIMER_TBL_NAKITAKIS_NEWs
		{
			get
			{
				return this.GetTable<DIMER_TBL_NAKITAKIS_NEW>();
			}
		}
		
		public System.Data.Linq.Table<TBLFATUEK> TBLFATUEKs
		{
			get
			{
				return this.GetTable<TBLFATUEK>();
			}
		}
		
		public System.Data.Linq.Table<DIM_NDI_EXIMBANK> DIM_NDI_EXIMBANKs
		{
			get
			{
				return this.GetTable<DIM_NDI_EXIMBANK>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DIMER_TBL_NAKITAKIS_NEW")]
	public partial class DIMER_TBL_NAKITAKIS_NEW : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _KALEM;
		
		private System.Nullable<double> _P_1;
		
		private System.Nullable<double> _P_2;
		
		private System.Nullable<double> _P_3;
		
		private System.Nullable<double> _P_4;
		
		private System.Nullable<double> _P_5;
		
		private System.Nullable<double> _P_6;
		
		private System.Nullable<double> _P_7;
		
		private System.Nullable<double> _P_8;
		
		private System.Nullable<double> _P_9;
		
		private System.Nullable<double> _P_10;
		
		private System.Nullable<double> _P_11;
		
		private System.Nullable<double> _P_12;
		
		private System.Nullable<double> _G_1;
		
		private System.Nullable<double> _G_2;
		
		private System.Nullable<double> _G_3;
		
		private System.Nullable<double> _G_4;
		
		private System.Nullable<double> _G_5;
		
		private System.Nullable<double> _G_6;
		
		private System.Nullable<double> _G_7;
		
		private System.Nullable<double> _G_8;
		
		private System.Nullable<double> _G_9;
		
		private System.Nullable<double> _G_10;
		
		private System.Nullable<double> _G_11;
		
		private System.Nullable<double> _G_12;
		
		private int _ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKALEMChanging(string value);
    partial void OnKALEMChanged();
    partial void OnP_1Changing(System.Nullable<double> value);
    partial void OnP_1Changed();
    partial void OnP_2Changing(System.Nullable<double> value);
    partial void OnP_2Changed();
    partial void OnP_3Changing(System.Nullable<double> value);
    partial void OnP_3Changed();
    partial void OnP_4Changing(System.Nullable<double> value);
    partial void OnP_4Changed();
    partial void OnP_5Changing(System.Nullable<double> value);
    partial void OnP_5Changed();
    partial void OnP_6Changing(System.Nullable<double> value);
    partial void OnP_6Changed();
    partial void OnP_7Changing(System.Nullable<double> value);
    partial void OnP_7Changed();
    partial void OnP_8Changing(System.Nullable<double> value);
    partial void OnP_8Changed();
    partial void OnP_9Changing(System.Nullable<double> value);
    partial void OnP_9Changed();
    partial void OnP_10Changing(System.Nullable<double> value);
    partial void OnP_10Changed();
    partial void OnP_11Changing(System.Nullable<double> value);
    partial void OnP_11Changed();
    partial void OnP_12Changing(System.Nullable<double> value);
    partial void OnP_12Changed();
    partial void OnG_1Changing(System.Nullable<double> value);
    partial void OnG_1Changed();
    partial void OnG_2Changing(System.Nullable<double> value);
    partial void OnG_2Changed();
    partial void OnG_3Changing(System.Nullable<double> value);
    partial void OnG_3Changed();
    partial void OnG_4Changing(System.Nullable<double> value);
    partial void OnG_4Changed();
    partial void OnG_5Changing(System.Nullable<double> value);
    partial void OnG_5Changed();
    partial void OnG_6Changing(System.Nullable<double> value);
    partial void OnG_6Changed();
    partial void OnG_7Changing(System.Nullable<double> value);
    partial void OnG_7Changed();
    partial void OnG_8Changing(System.Nullable<double> value);
    partial void OnG_8Changed();
    partial void OnG_9Changing(System.Nullable<double> value);
    partial void OnG_9Changed();
    partial void OnG_10Changing(System.Nullable<double> value);
    partial void OnG_10Changed();
    partial void OnG_11Changing(System.Nullable<double> value);
    partial void OnG_11Changed();
    partial void OnG_12Changing(System.Nullable<double> value);
    partial void OnG_12Changed();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    #endregion
		
		public DIMER_TBL_NAKITAKIS_NEW()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KALEM", DbType="VarChar(255)")]
		public string KALEM
		{
			get
			{
				return this._KALEM;
			}
			set
			{
				if ((this._KALEM != value))
				{
					this.OnKALEMChanging(value);
					this.SendPropertyChanging();
					this._KALEM = value;
					this.SendPropertyChanged("KALEM");
					this.OnKALEMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_1", DbType="Float")]
		public System.Nullable<double> P_1
		{
			get
			{
				return this._P_1;
			}
			set
			{
				if ((this._P_1 != value))
				{
					this.OnP_1Changing(value);
					this.SendPropertyChanging();
					this._P_1 = value;
					this.SendPropertyChanged("P_1");
					this.OnP_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_2", DbType="Float")]
		public System.Nullable<double> P_2
		{
			get
			{
				return this._P_2;
			}
			set
			{
				if ((this._P_2 != value))
				{
					this.OnP_2Changing(value);
					this.SendPropertyChanging();
					this._P_2 = value;
					this.SendPropertyChanged("P_2");
					this.OnP_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_3", DbType="Float")]
		public System.Nullable<double> P_3
		{
			get
			{
				return this._P_3;
			}
			set
			{
				if ((this._P_3 != value))
				{
					this.OnP_3Changing(value);
					this.SendPropertyChanging();
					this._P_3 = value;
					this.SendPropertyChanged("P_3");
					this.OnP_3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_4", DbType="Float")]
		public System.Nullable<double> P_4
		{
			get
			{
				return this._P_4;
			}
			set
			{
				if ((this._P_4 != value))
				{
					this.OnP_4Changing(value);
					this.SendPropertyChanging();
					this._P_4 = value;
					this.SendPropertyChanged("P_4");
					this.OnP_4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_5", DbType="Float")]
		public System.Nullable<double> P_5
		{
			get
			{
				return this._P_5;
			}
			set
			{
				if ((this._P_5 != value))
				{
					this.OnP_5Changing(value);
					this.SendPropertyChanging();
					this._P_5 = value;
					this.SendPropertyChanged("P_5");
					this.OnP_5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_6", DbType="Float")]
		public System.Nullable<double> P_6
		{
			get
			{
				return this._P_6;
			}
			set
			{
				if ((this._P_6 != value))
				{
					this.OnP_6Changing(value);
					this.SendPropertyChanging();
					this._P_6 = value;
					this.SendPropertyChanged("P_6");
					this.OnP_6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_7", DbType="Float")]
		public System.Nullable<double> P_7
		{
			get
			{
				return this._P_7;
			}
			set
			{
				if ((this._P_7 != value))
				{
					this.OnP_7Changing(value);
					this.SendPropertyChanging();
					this._P_7 = value;
					this.SendPropertyChanged("P_7");
					this.OnP_7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_8", DbType="Float")]
		public System.Nullable<double> P_8
		{
			get
			{
				return this._P_8;
			}
			set
			{
				if ((this._P_8 != value))
				{
					this.OnP_8Changing(value);
					this.SendPropertyChanging();
					this._P_8 = value;
					this.SendPropertyChanged("P_8");
					this.OnP_8Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_9", DbType="Float")]
		public System.Nullable<double> P_9
		{
			get
			{
				return this._P_9;
			}
			set
			{
				if ((this._P_9 != value))
				{
					this.OnP_9Changing(value);
					this.SendPropertyChanging();
					this._P_9 = value;
					this.SendPropertyChanged("P_9");
					this.OnP_9Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_10", DbType="Float")]
		public System.Nullable<double> P_10
		{
			get
			{
				return this._P_10;
			}
			set
			{
				if ((this._P_10 != value))
				{
					this.OnP_10Changing(value);
					this.SendPropertyChanging();
					this._P_10 = value;
					this.SendPropertyChanged("P_10");
					this.OnP_10Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_11", DbType="Float")]
		public System.Nullable<double> P_11
		{
			get
			{
				return this._P_11;
			}
			set
			{
				if ((this._P_11 != value))
				{
					this.OnP_11Changing(value);
					this.SendPropertyChanging();
					this._P_11 = value;
					this.SendPropertyChanged("P_11");
					this.OnP_11Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_12", DbType="Float")]
		public System.Nullable<double> P_12
		{
			get
			{
				return this._P_12;
			}
			set
			{
				if ((this._P_12 != value))
				{
					this.OnP_12Changing(value);
					this.SendPropertyChanging();
					this._P_12 = value;
					this.SendPropertyChanged("P_12");
					this.OnP_12Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_G_1", DbType="Float")]
		public System.Nullable<double> G_1
		{
			get
			{
				return this._G_1;
			}
			set
			{
				if ((this._G_1 != value))
				{
					this.OnG_1Changing(value);
					this.SendPropertyChanging();
					this._G_1 = value;
					this.SendPropertyChanged("G_1");
					this.OnG_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_G_2", DbType="Float")]
		public System.Nullable<double> G_2
		{
			get
			{
				return this._G_2;
			}
			set
			{
				if ((this._G_2 != value))
				{
					this.OnG_2Changing(value);
					this.SendPropertyChanging();
					this._G_2 = value;
					this.SendPropertyChanged("G_2");
					this.OnG_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_G_3", DbType="Float")]
		public System.Nullable<double> G_3
		{
			get
			{
				return this._G_3;
			}
			set
			{
				if ((this._G_3 != value))
				{
					this.OnG_3Changing(value);
					this.SendPropertyChanging();
					this._G_3 = value;
					this.SendPropertyChanged("G_3");
					this.OnG_3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_G_4", DbType="Float")]
		public System.Nullable<double> G_4
		{
			get
			{
				return this._G_4;
			}
			set
			{
				if ((this._G_4 != value))
				{
					this.OnG_4Changing(value);
					this.SendPropertyChanging();
					this._G_4 = value;
					this.SendPropertyChanged("G_4");
					this.OnG_4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_G_5", DbType="Float")]
		public System.Nullable<double> G_5
		{
			get
			{
				return this._G_5;
			}
			set
			{
				if ((this._G_5 != value))
				{
					this.OnG_5Changing(value);
					this.SendPropertyChanging();
					this._G_5 = value;
					this.SendPropertyChanged("G_5");
					this.OnG_5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_G_6", DbType="Float")]
		public System.Nullable<double> G_6
		{
			get
			{
				return this._G_6;
			}
			set
			{
				if ((this._G_6 != value))
				{
					this.OnG_6Changing(value);
					this.SendPropertyChanging();
					this._G_6 = value;
					this.SendPropertyChanged("G_6");
					this.OnG_6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_G_7", DbType="Float")]
		public System.Nullable<double> G_7
		{
			get
			{
				return this._G_7;
			}
			set
			{
				if ((this._G_7 != value))
				{
					this.OnG_7Changing(value);
					this.SendPropertyChanging();
					this._G_7 = value;
					this.SendPropertyChanged("G_7");
					this.OnG_7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_G_8", DbType="Float")]
		public System.Nullable<double> G_8
		{
			get
			{
				return this._G_8;
			}
			set
			{
				if ((this._G_8 != value))
				{
					this.OnG_8Changing(value);
					this.SendPropertyChanging();
					this._G_8 = value;
					this.SendPropertyChanged("G_8");
					this.OnG_8Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_G_9", DbType="Float")]
		public System.Nullable<double> G_9
		{
			get
			{
				return this._G_9;
			}
			set
			{
				if ((this._G_9 != value))
				{
					this.OnG_9Changing(value);
					this.SendPropertyChanging();
					this._G_9 = value;
					this.SendPropertyChanged("G_9");
					this.OnG_9Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_G_10", DbType="Float")]
		public System.Nullable<double> G_10
		{
			get
			{
				return this._G_10;
			}
			set
			{
				if ((this._G_10 != value))
				{
					this.OnG_10Changing(value);
					this.SendPropertyChanging();
					this._G_10 = value;
					this.SendPropertyChanged("G_10");
					this.OnG_10Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_G_11", DbType="Float")]
		public System.Nullable<double> G_11
		{
			get
			{
				return this._G_11;
			}
			set
			{
				if ((this._G_11 != value))
				{
					this.OnG_11Changing(value);
					this.SendPropertyChanging();
					this._G_11 = value;
					this.SendPropertyChanged("G_11");
					this.OnG_11Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_G_12", DbType="Float")]
		public System.Nullable<double> G_12
		{
			get
			{
				return this._G_12;
			}
			set
			{
				if ((this._G_12 != value))
				{
					this.OnG_12Changing(value);
					this.SendPropertyChanging();
					this._G_12 = value;
					this.SendPropertyChanged("G_12");
					this.OnG_12Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBLFATUEK")]
	public partial class TBLFATUEK : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _SUBE_KODU;
		
		private char _FKOD;
		
		private string _FATIRSNO;
		
		private string _CKOD;
		
		private string _ACIK1;
		
		private string _ACIK2;
		
		private string _ACIK3;
		
		private string _ACIK4;
		
		private string _ACIK5;
		
		private string _ACIK6;
		
		private string _ACIK7;
		
		private string _ACIK8;
		
		private string _ACIK9;
		
		private string _ACIK10;
		
		private string _ACIK11;
		
		private string _ACIK12;
		
		private string _ACIK13;
		
		private string _ACIK14;
		
		private string _ACIK15;
		
		private string _ACIK16;
		
		private string _S_YEDEK1;
		
		private string _S_YEDEK2;
		
		private string _S_YEDEK3;
		
		private string _S_YEDEK4;
		
		private System.Nullable<decimal> _F_YEDEK5;
		
		private System.Nullable<decimal> _F_YEDEK6;
		
		private System.Nullable<decimal> _F_YEDEK7;
		
		private System.Nullable<decimal> _F_YEDEK8;
		
		private System.Nullable<short> _I_YEDEK9;
		
		private System.Nullable<short> _I_YEDEK10;
		
		private System.Nullable<int> _G_YEDEK11;
		
		private string _OKCSERINO;
		
		private string _ZRAPORNO;
		
		private System.Nullable<System.DateTime> _OKCTARIH;
		
		private string _OKCFISNO;
		
		private string _OKCFISTIP;
		
		private System.Nullable<short> _PROFILEID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSUBE_KODUChanging(short value);
    partial void OnSUBE_KODUChanged();
    partial void OnFKODChanging(char value);
    partial void OnFKODChanged();
    partial void OnFATIRSNOChanging(string value);
    partial void OnFATIRSNOChanged();
    partial void OnCKODChanging(string value);
    partial void OnCKODChanged();
    partial void OnACIK1Changing(string value);
    partial void OnACIK1Changed();
    partial void OnACIK2Changing(string value);
    partial void OnACIK2Changed();
    partial void OnACIK3Changing(string value);
    partial void OnACIK3Changed();
    partial void OnACIK4Changing(string value);
    partial void OnACIK4Changed();
    partial void OnACIK5Changing(string value);
    partial void OnACIK5Changed();
    partial void OnACIK6Changing(string value);
    partial void OnACIK6Changed();
    partial void OnACIK7Changing(string value);
    partial void OnACIK7Changed();
    partial void OnACIK8Changing(string value);
    partial void OnACIK8Changed();
    partial void OnACIK9Changing(string value);
    partial void OnACIK9Changed();
    partial void OnACIK10Changing(string value);
    partial void OnACIK10Changed();
    partial void OnACIK11Changing(string value);
    partial void OnACIK11Changed();
    partial void OnACIK12Changing(string value);
    partial void OnACIK12Changed();
    partial void OnACIK13Changing(string value);
    partial void OnACIK13Changed();
    partial void OnACIK14Changing(string value);
    partial void OnACIK14Changed();
    partial void OnACIK15Changing(string value);
    partial void OnACIK15Changed();
    partial void OnACIK16Changing(string value);
    partial void OnACIK16Changed();
    partial void OnS_YEDEK1Changing(string value);
    partial void OnS_YEDEK1Changed();
    partial void OnS_YEDEK2Changing(string value);
    partial void OnS_YEDEK2Changed();
    partial void OnS_YEDEK3Changing(string value);
    partial void OnS_YEDEK3Changed();
    partial void OnS_YEDEK4Changing(string value);
    partial void OnS_YEDEK4Changed();
    partial void OnF_YEDEK5Changing(System.Nullable<decimal> value);
    partial void OnF_YEDEK5Changed();
    partial void OnF_YEDEK6Changing(System.Nullable<decimal> value);
    partial void OnF_YEDEK6Changed();
    partial void OnF_YEDEK7Changing(System.Nullable<decimal> value);
    partial void OnF_YEDEK7Changed();
    partial void OnF_YEDEK8Changing(System.Nullable<decimal> value);
    partial void OnF_YEDEK8Changed();
    partial void OnI_YEDEK9Changing(System.Nullable<short> value);
    partial void OnI_YEDEK9Changed();
    partial void OnI_YEDEK10Changing(System.Nullable<short> value);
    partial void OnI_YEDEK10Changed();
    partial void OnG_YEDEK11Changing(System.Nullable<int> value);
    partial void OnG_YEDEK11Changed();
    partial void OnOKCSERINOChanging(string value);
    partial void OnOKCSERINOChanged();
    partial void OnZRAPORNOChanging(string value);
    partial void OnZRAPORNOChanged();
    partial void OnOKCTARIHChanging(System.Nullable<System.DateTime> value);
    partial void OnOKCTARIHChanged();
    partial void OnOKCFISNOChanging(string value);
    partial void OnOKCFISNOChanged();
    partial void OnOKCFISTIPChanging(string value);
    partial void OnOKCFISTIPChanged();
    partial void OnPROFILEIDChanging(System.Nullable<short> value);
    partial void OnPROFILEIDChanged();
    #endregion
		
		public TBLFATUEK()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUBE_KODU", DbType="SmallInt NOT NULL")]
		public short SUBE_KODU
		{
			get
			{
				return this._SUBE_KODU;
			}
			set
			{
				if ((this._SUBE_KODU != value))
				{
					this.OnSUBE_KODUChanging(value);
					this.SendPropertyChanging();
					this._SUBE_KODU = value;
					this.SendPropertyChanged("SUBE_KODU");
					this.OnSUBE_KODUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FKOD", DbType="Char(1) NOT NULL", IsPrimaryKey=true)]
		public char FKOD
		{
			get
			{
				return this._FKOD;
			}
			set
			{
				if ((this._FKOD != value))
				{
					this.OnFKODChanging(value);
					this.SendPropertyChanging();
					this._FKOD = value;
					this.SendPropertyChanged("FKOD");
					this.OnFKODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FATIRSNO", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string FATIRSNO
		{
			get
			{
				return this._FATIRSNO;
			}
			set
			{
				if ((this._FATIRSNO != value))
				{
					this.OnFATIRSNOChanging(value);
					this.SendPropertyChanging();
					this._FATIRSNO = value;
					this.SendPropertyChanged("FATIRSNO");
					this.OnFATIRSNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CKOD", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CKOD
		{
			get
			{
				return this._CKOD;
			}
			set
			{
				if ((this._CKOD != value))
				{
					this.OnCKODChanging(value);
					this.SendPropertyChanging();
					this._CKOD = value;
					this.SendPropertyChanged("CKOD");
					this.OnCKODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACIK1", DbType="VarChar(100)")]
		public string ACIK1
		{
			get
			{
				return this._ACIK1;
			}
			set
			{
				if ((this._ACIK1 != value))
				{
					this.OnACIK1Changing(value);
					this.SendPropertyChanging();
					this._ACIK1 = value;
					this.SendPropertyChanged("ACIK1");
					this.OnACIK1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACIK2", DbType="VarChar(100)")]
		public string ACIK2
		{
			get
			{
				return this._ACIK2;
			}
			set
			{
				if ((this._ACIK2 != value))
				{
					this.OnACIK2Changing(value);
					this.SendPropertyChanging();
					this._ACIK2 = value;
					this.SendPropertyChanged("ACIK2");
					this.OnACIK2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACIK3", DbType="VarChar(100)")]
		public string ACIK3
		{
			get
			{
				return this._ACIK3;
			}
			set
			{
				if ((this._ACIK3 != value))
				{
					this.OnACIK3Changing(value);
					this.SendPropertyChanging();
					this._ACIK3 = value;
					this.SendPropertyChanged("ACIK3");
					this.OnACIK3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACIK4", DbType="VarChar(100)")]
		public string ACIK4
		{
			get
			{
				return this._ACIK4;
			}
			set
			{
				if ((this._ACIK4 != value))
				{
					this.OnACIK4Changing(value);
					this.SendPropertyChanging();
					this._ACIK4 = value;
					this.SendPropertyChanged("ACIK4");
					this.OnACIK4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACIK5", DbType="VarChar(100)")]
		public string ACIK5
		{
			get
			{
				return this._ACIK5;
			}
			set
			{
				if ((this._ACIK5 != value))
				{
					this.OnACIK5Changing(value);
					this.SendPropertyChanging();
					this._ACIK5 = value;
					this.SendPropertyChanged("ACIK5");
					this.OnACIK5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACIK6", DbType="VarChar(100)")]
		public string ACIK6
		{
			get
			{
				return this._ACIK6;
			}
			set
			{
				if ((this._ACIK6 != value))
				{
					this.OnACIK6Changing(value);
					this.SendPropertyChanging();
					this._ACIK6 = value;
					this.SendPropertyChanged("ACIK6");
					this.OnACIK6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACIK7", DbType="VarChar(100)")]
		public string ACIK7
		{
			get
			{
				return this._ACIK7;
			}
			set
			{
				if ((this._ACIK7 != value))
				{
					this.OnACIK7Changing(value);
					this.SendPropertyChanging();
					this._ACIK7 = value;
					this.SendPropertyChanged("ACIK7");
					this.OnACIK7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACIK8", DbType="VarChar(100)")]
		public string ACIK8
		{
			get
			{
				return this._ACIK8;
			}
			set
			{
				if ((this._ACIK8 != value))
				{
					this.OnACIK8Changing(value);
					this.SendPropertyChanging();
					this._ACIK8 = value;
					this.SendPropertyChanged("ACIK8");
					this.OnACIK8Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACIK9", DbType="VarChar(100)")]
		public string ACIK9
		{
			get
			{
				return this._ACIK9;
			}
			set
			{
				if ((this._ACIK9 != value))
				{
					this.OnACIK9Changing(value);
					this.SendPropertyChanging();
					this._ACIK9 = value;
					this.SendPropertyChanged("ACIK9");
					this.OnACIK9Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACIK10", DbType="VarChar(100)")]
		public string ACIK10
		{
			get
			{
				return this._ACIK10;
			}
			set
			{
				if ((this._ACIK10 != value))
				{
					this.OnACIK10Changing(value);
					this.SendPropertyChanging();
					this._ACIK10 = value;
					this.SendPropertyChanged("ACIK10");
					this.OnACIK10Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACIK11", DbType="VarChar(100)")]
		public string ACIK11
		{
			get
			{
				return this._ACIK11;
			}
			set
			{
				if ((this._ACIK11 != value))
				{
					this.OnACIK11Changing(value);
					this.SendPropertyChanging();
					this._ACIK11 = value;
					this.SendPropertyChanged("ACIK11");
					this.OnACIK11Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACIK12", DbType="VarChar(100)")]
		public string ACIK12
		{
			get
			{
				return this._ACIK12;
			}
			set
			{
				if ((this._ACIK12 != value))
				{
					this.OnACIK12Changing(value);
					this.SendPropertyChanging();
					this._ACIK12 = value;
					this.SendPropertyChanged("ACIK12");
					this.OnACIK12Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACIK13", DbType="VarChar(100)")]
		public string ACIK13
		{
			get
			{
				return this._ACIK13;
			}
			set
			{
				if ((this._ACIK13 != value))
				{
					this.OnACIK13Changing(value);
					this.SendPropertyChanging();
					this._ACIK13 = value;
					this.SendPropertyChanged("ACIK13");
					this.OnACIK13Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACIK14", DbType="VarChar(100)")]
		public string ACIK14
		{
			get
			{
				return this._ACIK14;
			}
			set
			{
				if ((this._ACIK14 != value))
				{
					this.OnACIK14Changing(value);
					this.SendPropertyChanging();
					this._ACIK14 = value;
					this.SendPropertyChanged("ACIK14");
					this.OnACIK14Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACIK15", DbType="VarChar(100)")]
		public string ACIK15
		{
			get
			{
				return this._ACIK15;
			}
			set
			{
				if ((this._ACIK15 != value))
				{
					this.OnACIK15Changing(value);
					this.SendPropertyChanging();
					this._ACIK15 = value;
					this.SendPropertyChanged("ACIK15");
					this.OnACIK15Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACIK16", DbType="VarChar(100)")]
		public string ACIK16
		{
			get
			{
				return this._ACIK16;
			}
			set
			{
				if ((this._ACIK16 != value))
				{
					this.OnACIK16Changing(value);
					this.SendPropertyChanging();
					this._ACIK16 = value;
					this.SendPropertyChanged("ACIK16");
					this.OnACIK16Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_YEDEK1", DbType="VarChar(8)")]
		public string S_YEDEK1
		{
			get
			{
				return this._S_YEDEK1;
			}
			set
			{
				if ((this._S_YEDEK1 != value))
				{
					this.OnS_YEDEK1Changing(value);
					this.SendPropertyChanging();
					this._S_YEDEK1 = value;
					this.SendPropertyChanged("S_YEDEK1");
					this.OnS_YEDEK1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_YEDEK2", DbType="VarChar(8)")]
		public string S_YEDEK2
		{
			get
			{
				return this._S_YEDEK2;
			}
			set
			{
				if ((this._S_YEDEK2 != value))
				{
					this.OnS_YEDEK2Changing(value);
					this.SendPropertyChanging();
					this._S_YEDEK2 = value;
					this.SendPropertyChanged("S_YEDEK2");
					this.OnS_YEDEK2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_YEDEK3", DbType="VarChar(8)")]
		public string S_YEDEK3
		{
			get
			{
				return this._S_YEDEK3;
			}
			set
			{
				if ((this._S_YEDEK3 != value))
				{
					this.OnS_YEDEK3Changing(value);
					this.SendPropertyChanging();
					this._S_YEDEK3 = value;
					this.SendPropertyChanged("S_YEDEK3");
					this.OnS_YEDEK3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_YEDEK4", DbType="VarChar(8)")]
		public string S_YEDEK4
		{
			get
			{
				return this._S_YEDEK4;
			}
			set
			{
				if ((this._S_YEDEK4 != value))
				{
					this.OnS_YEDEK4Changing(value);
					this.SendPropertyChanging();
					this._S_YEDEK4 = value;
					this.SendPropertyChanged("S_YEDEK4");
					this.OnS_YEDEK4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_YEDEK5", DbType="Decimal(28,8)")]
		public System.Nullable<decimal> F_YEDEK5
		{
			get
			{
				return this._F_YEDEK5;
			}
			set
			{
				if ((this._F_YEDEK5 != value))
				{
					this.OnF_YEDEK5Changing(value);
					this.SendPropertyChanging();
					this._F_YEDEK5 = value;
					this.SendPropertyChanged("F_YEDEK5");
					this.OnF_YEDEK5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_YEDEK6", DbType="Decimal(28,8)")]
		public System.Nullable<decimal> F_YEDEK6
		{
			get
			{
				return this._F_YEDEK6;
			}
			set
			{
				if ((this._F_YEDEK6 != value))
				{
					this.OnF_YEDEK6Changing(value);
					this.SendPropertyChanging();
					this._F_YEDEK6 = value;
					this.SendPropertyChanged("F_YEDEK6");
					this.OnF_YEDEK6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_YEDEK7", DbType="Decimal(28,8)")]
		public System.Nullable<decimal> F_YEDEK7
		{
			get
			{
				return this._F_YEDEK7;
			}
			set
			{
				if ((this._F_YEDEK7 != value))
				{
					this.OnF_YEDEK7Changing(value);
					this.SendPropertyChanging();
					this._F_YEDEK7 = value;
					this.SendPropertyChanged("F_YEDEK7");
					this.OnF_YEDEK7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_YEDEK8", DbType="Decimal(28,8)")]
		public System.Nullable<decimal> F_YEDEK8
		{
			get
			{
				return this._F_YEDEK8;
			}
			set
			{
				if ((this._F_YEDEK8 != value))
				{
					this.OnF_YEDEK8Changing(value);
					this.SendPropertyChanging();
					this._F_YEDEK8 = value;
					this.SendPropertyChanged("F_YEDEK8");
					this.OnF_YEDEK8Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_I_YEDEK9", DbType="SmallInt")]
		public System.Nullable<short> I_YEDEK9
		{
			get
			{
				return this._I_YEDEK9;
			}
			set
			{
				if ((this._I_YEDEK9 != value))
				{
					this.OnI_YEDEK9Changing(value);
					this.SendPropertyChanging();
					this._I_YEDEK9 = value;
					this.SendPropertyChanged("I_YEDEK9");
					this.OnI_YEDEK9Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_I_YEDEK10", DbType="SmallInt")]
		public System.Nullable<short> I_YEDEK10
		{
			get
			{
				return this._I_YEDEK10;
			}
			set
			{
				if ((this._I_YEDEK10 != value))
				{
					this.OnI_YEDEK10Changing(value);
					this.SendPropertyChanging();
					this._I_YEDEK10 = value;
					this.SendPropertyChanged("I_YEDEK10");
					this.OnI_YEDEK10Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_G_YEDEK11", DbType="Int")]
		public System.Nullable<int> G_YEDEK11
		{
			get
			{
				return this._G_YEDEK11;
			}
			set
			{
				if ((this._G_YEDEK11 != value))
				{
					this.OnG_YEDEK11Changing(value);
					this.SendPropertyChanging();
					this._G_YEDEK11 = value;
					this.SendPropertyChanged("G_YEDEK11");
					this.OnG_YEDEK11Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OKCSERINO", DbType="VarChar(25)")]
		public string OKCSERINO
		{
			get
			{
				return this._OKCSERINO;
			}
			set
			{
				if ((this._OKCSERINO != value))
				{
					this.OnOKCSERINOChanging(value);
					this.SendPropertyChanging();
					this._OKCSERINO = value;
					this.SendPropertyChanged("OKCSERINO");
					this.OnOKCSERINOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZRAPORNO", DbType="VarChar(25)")]
		public string ZRAPORNO
		{
			get
			{
				return this._ZRAPORNO;
			}
			set
			{
				if ((this._ZRAPORNO != value))
				{
					this.OnZRAPORNOChanging(value);
					this.SendPropertyChanging();
					this._ZRAPORNO = value;
					this.SendPropertyChanged("ZRAPORNO");
					this.OnZRAPORNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OKCTARIH", DbType="DateTime")]
		public System.Nullable<System.DateTime> OKCTARIH
		{
			get
			{
				return this._OKCTARIH;
			}
			set
			{
				if ((this._OKCTARIH != value))
				{
					this.OnOKCTARIHChanging(value);
					this.SendPropertyChanging();
					this._OKCTARIH = value;
					this.SendPropertyChanged("OKCTARIH");
					this.OnOKCTARIHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OKCFISNO", DbType="VarChar(25)")]
		public string OKCFISNO
		{
			get
			{
				return this._OKCFISNO;
			}
			set
			{
				if ((this._OKCFISNO != value))
				{
					this.OnOKCFISNOChanging(value);
					this.SendPropertyChanging();
					this._OKCFISNO = value;
					this.SendPropertyChanged("OKCFISNO");
					this.OnOKCFISNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OKCFISTIP", DbType="VarChar(50)")]
		public string OKCFISTIP
		{
			get
			{
				return this._OKCFISTIP;
			}
			set
			{
				if ((this._OKCFISTIP != value))
				{
					this.OnOKCFISTIPChanging(value);
					this.SendPropertyChanging();
					this._OKCFISTIP = value;
					this.SendPropertyChanged("OKCFISTIP");
					this.OnOKCFISTIPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROFILEID", DbType="SmallInt")]
		public System.Nullable<short> PROFILEID
		{
			get
			{
				return this._PROFILEID;
			}
			set
			{
				if ((this._PROFILEID != value))
				{
					this.OnPROFILEIDChanging(value);
					this.SendPropertyChanging();
					this._PROFILEID = value;
					this.SendPropertyChanged("PROFILEID");
					this.OnPROFILEIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DIM_NDI_EXIMBANK")]
	public partial class DIM_NDI_EXIMBANK : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<System.DateTime> _TARIH;
		
		private string _BELGENO;
		
		private string _BANKA_NO;
		
		private string _ACIKLAMA;
		
		private System.Nullable<System.DateTime> _VADE_TARIHI;
		
		private System.Nullable<char> _BA;
		
		private System.Nullable<decimal> _TUTAR;
		
		private System.Nullable<byte> _DOVTIP;
		
		private System.Nullable<decimal> _DOVIZTUT;
		
		private System.Nullable<decimal> _FAIZ_ORANI;
		
		private System.Nullable<decimal> _D_KUR;
		
		private System.Nullable<char> _DURUM;
		
		private System.Nullable<char> _ONAYTIPI;
		
		private System.Nullable<int> _ONAYNUM;
		
		private int _ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTARIHChanging(System.Nullable<System.DateTime> value);
    partial void OnTARIHChanged();
    partial void OnBELGENOChanging(string value);
    partial void OnBELGENOChanged();
    partial void OnBANKA_NOChanging(string value);
    partial void OnBANKA_NOChanged();
    partial void OnACIKLAMAChanging(string value);
    partial void OnACIKLAMAChanged();
    partial void OnVADE_TARIHIChanging(System.Nullable<System.DateTime> value);
    partial void OnVADE_TARIHIChanged();
    partial void OnBAChanging(System.Nullable<char> value);
    partial void OnBAChanged();
    partial void OnTUTARChanging(System.Nullable<decimal> value);
    partial void OnTUTARChanged();
    partial void OnDOVTIPChanging(System.Nullable<byte> value);
    partial void OnDOVTIPChanged();
    partial void OnDOVIZTUTChanging(System.Nullable<decimal> value);
    partial void OnDOVIZTUTChanged();
    partial void OnFAIZ_ORANIChanging(System.Nullable<decimal> value);
    partial void OnFAIZ_ORANIChanged();
    partial void OnD_KURChanging(System.Nullable<decimal> value);
    partial void OnD_KURChanged();
    partial void OnDURUMChanging(System.Nullable<char> value);
    partial void OnDURUMChanged();
    partial void OnONAYTIPIChanging(System.Nullable<char> value);
    partial void OnONAYTIPIChanged();
    partial void OnONAYNUMChanging(System.Nullable<int> value);
    partial void OnONAYNUMChanged();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    #endregion
		
		public DIM_NDI_EXIMBANK()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TARIH", DbType="DateTime")]
		public System.Nullable<System.DateTime> TARIH
		{
			get
			{
				return this._TARIH;
			}
			set
			{
				if ((this._TARIH != value))
				{
					this.OnTARIHChanging(value);
					this.SendPropertyChanging();
					this._TARIH = value;
					this.SendPropertyChanged("TARIH");
					this.OnTARIHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BELGENO", DbType="VarChar(15)")]
		public string BELGENO
		{
			get
			{
				return this._BELGENO;
			}
			set
			{
				if ((this._BELGENO != value))
				{
					this.OnBELGENOChanging(value);
					this.SendPropertyChanging();
					this._BELGENO = value;
					this.SendPropertyChanged("BELGENO");
					this.OnBELGENOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BANKA_NO", DbType="VarChar(15)")]
		public string BANKA_NO
		{
			get
			{
				return this._BANKA_NO;
			}
			set
			{
				if ((this._BANKA_NO != value))
				{
					this.OnBANKA_NOChanging(value);
					this.SendPropertyChanging();
					this._BANKA_NO = value;
					this.SendPropertyChanged("BANKA_NO");
					this.OnBANKA_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACIKLAMA", DbType="VarChar(50)")]
		public string ACIKLAMA
		{
			get
			{
				return this._ACIKLAMA;
			}
			set
			{
				if ((this._ACIKLAMA != value))
				{
					this.OnACIKLAMAChanging(value);
					this.SendPropertyChanging();
					this._ACIKLAMA = value;
					this.SendPropertyChanged("ACIKLAMA");
					this.OnACIKLAMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VADE_TARIHI", DbType="DateTime")]
		public System.Nullable<System.DateTime> VADE_TARIHI
		{
			get
			{
				return this._VADE_TARIHI;
			}
			set
			{
				if ((this._VADE_TARIHI != value))
				{
					this.OnVADE_TARIHIChanging(value);
					this.SendPropertyChanging();
					this._VADE_TARIHI = value;
					this.SendPropertyChanged("VADE_TARIHI");
					this.OnVADE_TARIHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BA", DbType="Char(1)")]
		public System.Nullable<char> BA
		{
			get
			{
				return this._BA;
			}
			set
			{
				if ((this._BA != value))
				{
					this.OnBAChanging(value);
					this.SendPropertyChanging();
					this._BA = value;
					this.SendPropertyChanged("BA");
					this.OnBAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TUTAR", DbType="Decimal(28,8)")]
		public System.Nullable<decimal> TUTAR
		{
			get
			{
				return this._TUTAR;
			}
			set
			{
				if ((this._TUTAR != value))
				{
					this.OnTUTARChanging(value);
					this.SendPropertyChanging();
					this._TUTAR = value;
					this.SendPropertyChanged("TUTAR");
					this.OnTUTARChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOVTIP", DbType="TinyInt")]
		public System.Nullable<byte> DOVTIP
		{
			get
			{
				return this._DOVTIP;
			}
			set
			{
				if ((this._DOVTIP != value))
				{
					this.OnDOVTIPChanging(value);
					this.SendPropertyChanging();
					this._DOVTIP = value;
					this.SendPropertyChanged("DOVTIP");
					this.OnDOVTIPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOVIZTUT", DbType="Decimal(28,8)")]
		public System.Nullable<decimal> DOVIZTUT
		{
			get
			{
				return this._DOVIZTUT;
			}
			set
			{
				if ((this._DOVIZTUT != value))
				{
					this.OnDOVIZTUTChanging(value);
					this.SendPropertyChanging();
					this._DOVIZTUT = value;
					this.SendPropertyChanged("DOVIZTUT");
					this.OnDOVIZTUTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FAIZ_ORANI", DbType="Decimal(28,8)")]
		public System.Nullable<decimal> FAIZ_ORANI
		{
			get
			{
				return this._FAIZ_ORANI;
			}
			set
			{
				if ((this._FAIZ_ORANI != value))
				{
					this.OnFAIZ_ORANIChanging(value);
					this.SendPropertyChanging();
					this._FAIZ_ORANI = value;
					this.SendPropertyChanged("FAIZ_ORANI");
					this.OnFAIZ_ORANIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D_KUR", DbType="Decimal(28,8)")]
		public System.Nullable<decimal> D_KUR
		{
			get
			{
				return this._D_KUR;
			}
			set
			{
				if ((this._D_KUR != value))
				{
					this.OnD_KURChanging(value);
					this.SendPropertyChanging();
					this._D_KUR = value;
					this.SendPropertyChanged("D_KUR");
					this.OnD_KURChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DURUM", DbType="Char(1)")]
		public System.Nullable<char> DURUM
		{
			get
			{
				return this._DURUM;
			}
			set
			{
				if ((this._DURUM != value))
				{
					this.OnDURUMChanging(value);
					this.SendPropertyChanging();
					this._DURUM = value;
					this.SendPropertyChanged("DURUM");
					this.OnDURUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ONAYTIPI", DbType="Char(1)")]
		public System.Nullable<char> ONAYTIPI
		{
			get
			{
				return this._ONAYTIPI;
			}
			set
			{
				if ((this._ONAYTIPI != value))
				{
					this.OnONAYTIPIChanging(value);
					this.SendPropertyChanging();
					this._ONAYTIPI = value;
					this.SendPropertyChanged("ONAYTIPI");
					this.OnONAYTIPIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ONAYNUM", DbType="Int")]
		public System.Nullable<int> ONAYNUM
		{
			get
			{
				return this._ONAYNUM;
			}
			set
			{
				if ((this._ONAYNUM != value))
				{
					this.OnONAYNUMChanging(value);
					this.SendPropertyChanging();
					this._ONAYNUM = value;
					this.SendPropertyChanged("ONAYNUM");
					this.OnONAYNUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
