#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinansAsistan.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;


	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name = "DIMIN2022")]
	public partial class dbDiminDataContext : System.Data.Linq.DataContext
	{

		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();

		#region Extensibility Method Definitions
		partial void OnCreated();
		partial void InsertDIMER_TBL_NAKITAKIS_NEW(DIMER_TBL_NAKITAKIS_NEW instance);
		partial void UpdateDIMER_TBL_NAKITAKIS_NEW(DIMER_TBL_NAKITAKIS_NEW instance);
		partial void DeleteDIMER_TBL_NAKITAKIS_NEW(DIMER_TBL_NAKITAKIS_NEW instance);
		partial void InsertTBLFATUEK(TBLFATUEK instance);
		partial void UpdateTBLFATUEK(TBLFATUEK instance);
		partial void DeleteTBLFATUEK(TBLFATUEK instance);
		partial void InsertDIM_NDI_EXIMBANK(DIM_NDI_EXIMBANK instance);
		partial void UpdateDIM_NDI_EXIMBANK(DIM_NDI_EXIMBANK instance);
		partial void DeleteDIM_NDI_EXIMBANK(DIM_NDI_EXIMBANK instance);
		#endregion

		public dbDiminDataContext() :
				base(global::FinansAsistan.Properties.Settings.Default.DIMIN2022, mappingSource)
		{
			OnCreated();
		}

		public dbDiminDataContext(string connection) :
				base(connection, mappingSource)
		{
			OnCreated();
		}

		public dbDiminDataContext(System.Data.IDbConnection connection) :
				base(connection, mappingSource)
		{
			OnCreated();
		}

		public dbDiminDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) :
				base(connection, mappingSource)
		{
			OnCreated();
		}

		public dbDiminDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) :
				base(connection, mappingSource)
		{
			OnCreated();
		}

		public System.Data.Linq.Table<DIMER_TBL_NAKITAKIS_NEW> DIMER_TBL_NAKITAKIS_NEWs
		{
			get
			{
				return this.GetTable<DIMER_TBL_NAKITAKIS_NEW>();
			}
		}

		public System.Data.Linq.Table<TBLFATUEK> TBLFATUEKs
		{
			get
			{
				return this.GetTable<TBLFATUEK>();
			}
		}

		public System.Data.Linq.Table<DIM_NDI_EXIMBANK> DIM_NDI_EXIMBANKs
		{
			get
			{
				return this.GetTable<DIM_NDI_EXIMBANK>();
			}
		}
	}


}
#pragma warning restore 1591
