//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinansAsistan.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DMRSQL\\DATASRV;Initial Catalog=DIMER2022;Persist Security Info=True;U" +
            "ser ID=RAPORLAMA;Password=Rapor+21?$")]
        public string DIMER2022 {
            get {
                return ((string)(this["DIMER2022"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.131\\DATASRV;Initial Catalog=DIMIN2022;Persist Security Info" +
            "=True;User ID=RAPORLAMA;Password=Rapor+21?$")]
        public string DIMIN2022 {
            get {
                return ((string)(this["DIMIN2022"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.131\\DATASRV;Initial Catalog=DMINERAL2022;Persist Security I" +
            "nfo=True;User ID=RAPORLAMA;Password=Rapor+21?$")]
        public string DMINERAL2022ConnectionString {
            get {
                return ((string)(this["DMINERAL2022ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.131\\DATASRV;Initial Catalog=DIMER2022;Persist Security Info" +
            "=True;User ID=RAPORLAMA;Password=Rapor+21?$")]
        public string DIMER2022ConnectionString {
            get {
                return ((string)(this["DIMER2022ConnectionString"]));
            }
        }
    }
}
